// File generated by FlutterFire CLI// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfT-Q8gzoICZQTH2OIfL8DszBw_3_KcSs',
    appId: '1:310450925479:web:5ab15bc07149c66d4d5082',
    messagingSenderId: '310450925479',
    projectId: 'fir-15aed',
    authDomain: 'fir-15aed.firebaseapp.com',
    storageBucket: 'fir-15aed.appspot.com',
    measurementId: 'G-Q0SXQEXRSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6_OljR4PX0fGe6dbIZS3Ex-itoasKTjU',
    appId: '1:310450925479:android:3c1d1ca9795b8cb44d5082',
    messagingSenderId: '310450925479',
    projectId: 'fir-15aed',
    storageBucket: 'fir-15aed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE21fldYKRP09uz-sW_zK74cptkXmpPOU',
    appId: '1:310450925479:ios:cd2f876ce7e03ef14d5082',
    messagingSenderId: '310450925479',
    projectId: 'fir-15aed',
    storageBucket: 'fir-15aed.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE21fldYKRP09uz-sW_zK74cptkXmpPOU',
    appId: '1:310450925479:ios:cd2f876ce7e03ef14d5082',
    messagingSenderId: '310450925479',
    projectId: 'fir-15aed',
    storageBucket: 'fir-15aed.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfT-Q8gzoICZQTH2OIfL8DszBw_3_KcSs',
    appId: '1:310450925479:web:7d7b04cd6df2ab7a4d5082',
    messagingSenderId: '310450925479',
    projectId: 'fir-15aed',
    authDomain: 'fir-15aed.firebaseapp.com',
    storageBucket: 'fir-15aed.appspot.com',
    measurementId: 'G-KZM2WKT191',
  );
}
